vich_uploader:
    db_driver: orm
    mappings:
        livre_couverture:
            uri_prefix: /assets/img
            upload_destination: '%kernel.project_dir%/public/assets/img'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
